# Generated by Django 2.0 on 2020-01-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WM_Market',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=1000)),
                ('DbName', models.CharField(max_length=1000)),
                ('ConnectionString', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'WM_Market',
            },
        ),
        migrations.CreateModel(
            name='WM_MarketPropertyData',
            fields=[
                ('PropertyDataID', models.IntegerField(primary_key=True, serialize=False)),
                ('PropertyID', models.IntegerField()),
                ('PropertyValue', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'WM_MarketPropertyData',
            },
        ),
        migrations.CreateModel(
            name='WM_MarketPropertyDataElements',
            fields=[
                ('PropertyID', models.IntegerField(primary_key=True, serialize=False)),
                ('PropertyName', models.CharField(max_length=250)),
                ('Description', models.CharField(max_length=750)),
            ],
            options={
                'verbose_name': 'WM_MarketPropertyDataElements',
            },
        ),
    ]
